### ISSUE TITLE
Should gl::clear() use a scoped depth mask?

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1084]
[This line](https://github.com/cinder/Cinder/blob/4958bfa17ac7a9e078510880f0d39522b0a48989/src/cinder/gl/wrapper.cpp#L189).  Seems like it might be leaking `depth mask = true`, but then not sure how we haven't seen a bug related to that come up in the wild.

**Comment by paulhoux** [comment]
I think you are right, it would be better to scope it.

But the reason we haven't seen any issues around this is because, as you know, the depth buffer test must be enabled in order to actually write something to it. If it's not, then subsequent draw calls will still not write to the depth buffer, even if ```glDepthMask(true)``` was called. In other words, in practice it does not matter whether or not the call to ```glDepthMask``` is scoped or not.

**Comment by andrewfb** [comment]
Addressed by #1123
