### ISSUE TITLE
LogManager indiscriminately removes loggers by type

### ISSUE THREAD

**Issue by lucasvickers** [cinder/Cinder#1107]
@richardeakin following our convo last night.

LoggerImplMulti's [removal](https://github.com/cinder/Cinder/blob/master/src/cinder/Log.cpp#L362-L369) routine remove any logger that matches a type.  Therefore it relies on only having one Logger of each type in the stack.

LoggerImplMulti's [add](https://github.com/cinder/Cinder/blob/master/src/cinder/Log.cpp#L53) routine, on the other hand, blindly pushes back Logger pointers.

The end result is that combining the helper functions such as ```enableFileLogging``` and the advanced usage of adding your own loggers via ```addLogger``` can create unexpected results.

Take for example the code below
```
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"
#include "cinder/Log.h"

#include <algorithm>

using namespace ci;
using namespace ci::app;
using namespace std;

class RandomTestApp : public App {
  public:
	void setup() override;
	void mouseDown( MouseEvent event ) override;
	void keyDown( KeyEvent event ) override;
	void update() override;
	void draw() override;
	
protected:
	log::LoggerFile *log;
};

void RandomTestApp::setup()
{
	log = new log::LoggerFile( "/tmp/custom.log", true );
	
	log::manager()->addLogger( log );
	log::manager()->enableFileLogging( "/tmp/managed.log", true );
}

void RandomTestApp::mouseDown( MouseEvent event )
{
	CI_LOG_I( "test log" );
}

void RandomTestApp::keyDown( KeyEvent event )
{
	log::manager()->disableFileLogging();
	CI_LOG_I( "removed the managed log." );
}

void RandomTestApp::update()
{
}

void RandomTestApp::draw()
{
	gl::clear( Color( 0, 0, 0 ) ); 
}

CINDER_APP( RandomTestApp, RendererGl )
```
If you do the following steps.

1.  Run it
1.  Click the mouse
1.  ```tail -f /tmp/manage.log /tmp/custom.log```
1.  Click the mouse

Then the results you get are not as expected:
```
$ tail -f managed.log custom.log 

==> managed.log <==
|info   | 2015-09-09.21:03:28 virtual void RandomTestApp::mouseDown(cinder::app::MouseEvent)[34] test log

==> custom.log <==
|info   | 2015-09-09.21:03:28 virtual void RandomTestApp::mouseDown(cinder::app::MouseEvent)[34] test log

==> managed.log <==
|info   | 2015-09-09.21:03:28 virtual void RandomTestApp::keyDown(cinder::app::KeyEvent)[40] removed the managed log.
```
**Notice** that the managed log remained, even though it _should_ have been the removed log.

I see three solutions

1. We simply tell people not to mix the basic functionality with the advanced functionality.
2. We only allow one type of Logger to be active at a time.
3. LoggerImplMulti keeps track of pointers to _internally managed_ loggers (i.e. ```enableFileLogging```, ```disableFileLogging```) and, we remove by pointer value not Logger type.  I could find a clever way so we don't need to add code every time we add a Logger type.

I think 2 is the way to go.
I think 1 is limiting.
I think 3 is wonky since you'd have to track all of your logger pointers otherwise you'd lose track of them if you did a call such as ```log::manager()->addLogger( new log::LoggerFile( "/tmp/log.log");```

Thoughts?

**Comment by richardeakin** [comment]
I think if we wanted to take on the extra maintenance burden, we could have LogManager hold pointers to it's managed loggers, one for each type that it knows how to manage. Then we could lift the limitation of only one type of Logger at a time completely, so you could do the following if, for some strange reason, you wanted to:

```cpp
log::manager()->addLogger( new log::LoggerFile( "/tmp/joe.log", true ) );
log::manager()->addLogger( new log::LoggerFile( "/tmp/blow.log", false ) );
```

However the method I proposed adding in PR #1103 would then be a bit more limited, as it would just return the first `LoggerFile` rather than the only `LoggerFile`. Not the end of the world, but then I think neither is only allowing one type of Logger at a time, at least for now. So yea, I say 2. is the way to go at  this time.

To do solution 2., we just need LoggerMulti to remove any exiting logger by type before adding a new one, right?

I'm going to merge #1103 unless you see any problems there, so that you can continue on with the stuff you're doing in Log.h.

**Comment by lucasvickers** [comment]
#1103 merge seems fine to me.  I may wind up changing it a little based on what we decide -- but for now merge it.

I don't see an extra maintenance burden for having pointers to managed loggers.  This is because we have to write helper functions for those managed loggers anyway.

With that said, I do see how suddenly the ```findType``` in #1103 becomes confusing.  We could just return a vector instead, and it's on the user to figure out which one they care about.  We could also do ```findType``` and ```getManagedLoggerConsole```, etc.  It's more helper functions but it gives explicit access to the managed logger.  If you're adding your own loggers you should probably keep track of their pointers anyway.

I actually don't think your example is so farfetched.. imagine
```
log::manager()->addLogger( new log::LoggerFile( "/tmp/history.log", true ) );
log::manager()->addLogger( new log::LoggerFile( "/tmp/last-run.log", false ) );
```

After talking, I vote for 3, and I also would then add some ```getManagedLogger_____``` routines.

**Comment by lucasvickers** [comment]
Take a look at [this](https://github.com/cinder/Cinder/commit/eecde80bae39a5e19ea947880a5e21d6f0f8d848) commit.  My changes remove the need for [logic](https://github.com/cinder/Cinder/blob/master/src/cinder/Log.cpp#L161-L168) that deals with a Logger* that's a _non LoggerMulti_ and a Logger that _is a LoggerMulti_.  I think this simplified things quite a bit.

I tested against the cases in DebugTest, but I need to do more extensive testing.  If you strongly object to this I'd appreciate your input before I write those tests.  I'll wait for your feedback before I proceed with anything.

The arguments against what I did (that I can think of):
- Always using the LoggerMulti means that in the default state (only a LoggerConsole) we are paying for the extra overhead of LoggerMulti.  
  - To this I would respond, the overhead is minimal and the code is cleaner so I consider it a fair tradeoff.  Not to mention we have used the LoggerMulti extensively and it clearly doesn't have performance issues.
- We need to keep track of pointers for each of the managed Logger types for the helper functions.
  - To this I would respond, we were previously keeping track of booleans, this is not all that different.

The argument for what I did:
- Clean way of accessing all Loggers, or all loggers of specific types from the LogManager.
- Since loggers are now internally managed by pointer values not types, any combination of loggers can be added or removed (fixing the problem this issue ticket relates to)

**Comment by lucasvickers** [comment]
Rich, when you have a sec please give me your input on this.  I'd like to move forward with this direction.

**Comment by richardeakin** [comment]
We've been discussing this a bit internally and over email, and decided that the LogManager-managed Loggers were probably not a great idea to start with. They require us adding a set of methods to LogManager itself, instead of letting LogManager just do the bookkeeping of an arbitrary set of loggers. So, instead of calling:

```cpp
log::manager()->enableFileLogging();
...
log::manager()->disableFileLogging();
```

You will call:

```cpp
auto loggerFile = new LoggerFile();
log::manager()->addLogger( loggerFile );
...
log::manager()->removeLogger( loggerFile );
```

We could make this even more convenient by adding a new freestanding function to the ci::log:: namespace:

```cpp
auto logger = log::addLogger( new LoggerFile );
```
or even:
```cpp
auto logger = log::makeLogger<LoggerFile>( "mylog.txt", true );
```

We are also considering to roll `LoggerMulti` directly into the `LogManager` (it would own a vector of `Logger`s), but there are thread safety complications so not entirely sure if this will make it into 0.9.0 or not. API modifications are priority so we can get those all out of the way now before a major release.

**Comment by lucasvickers** [comment]
Restructure has resolved this
