### ISSUE TITLE
ObjLoader fails to parse OBJ files with line continuations marked by `\`

### ISSUE THREAD

**Issue by sansumbrella** [cinder/Cinder#1121]
When loading OBJ files that break vertex or face properties across multiple lines, parsing fails with an exception: `stoi: no conversion`.

Example problematic line (note the trailing `\` to indicate continuation on the following line):
```
f 27050/26938/27050 27041/26929/27041 27044/26932/27044 \
 27047/26935/27047
```

OSX Finder and Unity3D both parse the OBJ successfully, so I would expect the Cinder parser to handle this, too.

**Comment by sansumbrella** [comment]
I'll have a look to see whether I can handle the `\` continuation marker.

**Comment by sansumbrella** [comment]
It seems like parsing `\` at the end of a line is something that should be handled by `IstreamCinder::readLine`. At least on Unix systems, I believe this is used consistently to mean "treat the next line as a continuation of the current line."

**Comment by richardeakin** [comment]
end-of-line `\`'s are not universal to all forms of text, or data streams for that matter, which is what IStreamCinder is meant to do. I think the `\`'s should be interpreted during ObjLoader's string parsing phase, iff it is part of the spec.

**Comment by sansumbrella** [comment]
That format was output by Rhino's OBJ exporter. I favor works with major software over conforms rigidly to spec (as our JSON parser judiciously ignores the spec's ban on comments). So to me it's definite that the ObjLoader at least should handle the `\`.

I would definitely have started with the OBJ Loader's text parsing, but it's using IStreamCinder, which places ObjLoader too late in the pipeline to be able to handle this parsing without including all of the IStreamCinder functionality directly in the loader.

Maybe an additional method for IStreamCinder is warranted?

```
std::string readLineWithContinuation(char continuation);
```

**Comment by sansumbrella** [comment]
Updated PR to add a method for handling the continuation character instead of modifying the default readLine method.

**Comment by richardeakin** [comment]
Yea I think it's a good idea to support backslashes as line continuation for all of the reasons you've listed, although it seems like ObjLoader would still be a better place to handle this logic, rather than opening up the possibility of parsing some other type of string wrong that has backslashes.

Couldn't these lines [here](https://github.com/cinder/Cinder/blob/ebe3cc4e55dc8651c4bffb0946310763ce67084e/src/cinder/ObjLoader.cpp#L153-L154) be modified so that if the `line` string's last charactoer is `\` then you concatenate it with the next line? Might be easier with an extra private method in ObjLoader to read the (possibly) concatenated lines, but seems pretty straightforward there although I haven't looked at that class in detail.

**Comment by sansumbrella** [comment]
Any opinion on the addition of a separate method for `readLineWithContinuation`? It seems like it may come up in other circumstances and would be nice to support.

Otherwise, yeah, we can `substr` and concatenate inside ObjLoader. Definitely feels nicer to me to not have extra string manipulation happening in there, though.

**Comment by meshula** [comment]
Looks like consensus already, just confirming that parsing backslash is important. All parsers I'm responsible for test explicitly for backslash. I've toyed with things like readLineWithContinuation but end up not using them because there are always funny exceptions where you might actually want to preserve the split, and so you end up with extra logic anyway to call one routine or the other depending on tests on corner cases. The goofy readLine variant I DO use a lot is one that automatically elides comments, either #, //, or /*  */

**Comment by andrewfb** [comment]
Just expressing agreement with the above; I agree with the idea that the OBJ loader should support this, and would be inclined to isolate that logic to the OBJ loader itself for the reasons Nick cited. Hard problem to really solve generically, so let's just solve it for OBJs for now.

**Comment by sansumbrella** [comment]
PR #1129 solves the issue for OBJs.
