### ISSUE TITLE
Using Eclipse with Cinder

### ISSUE THREAD

**Issue by DQvsRA** [cinder/Cinder#1159]
Hello.
I would like to use Eclipse CPP to work with Cinder framework. Can you give me a proper instructions to do that?

**Comment by richardeakin** [comment]
We're not planning any official support for using Eclipse with cinder, one of the reasons is because those who have found it to run very slow.

Have you looked at using [CLion](https://www.jetbrains.com/clion/)?  You need cmake files for this, I've got a [branch here](https://github.com/richardeakin/Cinder/tree/cmake) that was an experiment with cmake and it seems to work fairly well with CLion. Check the forum for similar endeavors in the community..

**Comment by DQvsRA** [comment]
I use Eclipse for different languages and i wrote and compile C program for AVR and ARM throw it, and it's work fine ... Any way i will try CLion. Thank you.
