### ISSUE TITLE
visual studio 2015 compiled version?

### ISSUE THREAD

**Issue by mmoh** [cinder/Cinder#1162]
It would be incredibly helpful if  we had compiled versions for visual studio 2015.

**Comment by paulhoux** [comment]
Are you having problems compiling Cinder yourself? If so, let us know.

**Comment by mmoh** [comment]
No problems compiling Cinder. However it does take time and opening the examples project files takes a lot of time to parse and convert when opening in VS2015. In any case seeing that anyone new will likely have or will upgrade to VS2015 in the near future I think there is some merit and benefits to offering a VS2015 version alongside VS2013 (if need be).

**Comment by paulhoux** [comment]
You're absolutely right, of course, and Cinder will see official support for VS2015 in the future. In fact, it should already compile in VS2015 without needing any modifications. 

Adding the .lib files to the repository would increase the download size considerably, which is part of the reason why there is no precompiled version for VS2015 as of now.

I am using VS2015 myself since a few months. I chose to install it next to VS2013, so that I have both the v120 and v140 toolsets available. That way, I can choose not to convert the project files when opening them and simply use them as VS2013 projects. This saves quite a lot of time.

**Comment by mmoh** [comment]
Great, thank you. Looking forward to it!

**Comment by fei4xu** [comment]
We should add 2015 compiled version on https://libcinder.org/download ( or replace the VS2013 version).
