### ISSUE TITLE
Image store support

### ISSUE THREAD

**Issue by acterhd** [cinder/Cinder#1184]
Why Cinder does not support image store feature?

**Comment by richardeakin** [comment]
What do you mean by 'image store'?

**Comment by ryanbartley** [comment]
Image Store is a [function](https://www.opengl.org/sdk/docs/man/html/imageStore.xhtml) in glsl, supported in OpenGL 4.2 and above and it is used inside of compute shaders. And in this case, if you are on Windows and if the OpenGL driver on the computer supports it, then you can use it un-hindered in Cinder. In other words, Cinder doesn't specifically hinder any functionality provided by the driver, especially in Glsl. MacOSX and iOS internally do not support it because they only support OpenGL 4.1.
