### ISSUE TITLE
Cross-platform cibuild

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#1250]
Would you be open to making the cmake build system cross-platform? It would make command line development possible on all platforms, improve cross-platform development and automated testing.

**Comment by pizthewiz** [comment]
While I tend to agree it would be convenient, I think it is worth mentioning that additional build infrastructure could add some complexity to development and contributions as project changes would need to be made in both the native project files (Xcode, VS) _and_ `CMakeFiles`. Also, the OS X and iOS targets support command line compile via `xcodebuild`, but I'd have to imagine automated testing tools like [Travis CI](https://travis-ci.org) support native project formats anyways no?

**Comment by richardeakin** [comment]
@gaborpapp we've begun working on cross platform cmake support although we still have a fair way to go. It started in Hai's [cmake](https://github.com/chaoticbob/Cinder/tree/cmake) branch, there is a [PR here](https://github.com/chaoticbob/Cinder/pull/83) that makes it functional only on Mac OS X. Currently the plan is that once it is a bit further along, we'll push a cmake branch to the main repo and begin getting community feedback. We're still exploring options as far as structure and what features in cmake to make use of, so please feel free to help out however you see fit.

@pizthewiz part of the rationale for adding cross-platform cmake is that we already need it as the build system for both linux and android. Then, you have Xcode which is lousy for editing C++, so it is nice to have an alternative there too. At this point, we might as well add the other platforms as it can be done in a way that doesn't require much maintenance (using helper modules).

As far as a personal preference goes, I've been using cmake + CLion more and more over the last few months and I very much prefer modifying project configurations using code rather than a gui, especially for anything beyond a basic sample. I'm sure there are others who feel similarly, so it is nice to give these people an additional option for how they'll build things.

**Comment by gaborpapp** [comment]
Thanks @richardeakin. I'm looking forward to testing this. I was always building cinder applications from the command line using scons. I'm very glad that cinder will support this. I move to cmake as this is the preferred build system for cinder now. I'm curious about your windows implementation, though. I used cygwin there, which was not ideal, but better than the default windows shell.

I'm closing this issue as work has begun on this already.
