### ISSUE TITLE
Refactoring platform-specific preprocessor macros

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1303]
In light of adding support for a few more platforms, the current discussion has been to refactor the macros to be:

**Everywhere**: CINDER_CINDER
**Platform-specific “leaves”**: CINDER_LINUX, CINDER_MAC, CINDER_IOS, CINDER_TVOS, CINDER_ANDROID, CINDER_MSW_DESKTOP, CINDER_MSW_UNIVERSAL
**All Windows variants**: CINDER_MSW
**Linux, OS X, iOS, tvOS, Android**: CINDER_POSIX
**OS X, iOS, tvOS**: CINDER_COCOA
**iOS, tvOS**: CINDER_COCOA_TOUCH

**Comment by pizthewiz** [comment]
The `CINDER_COCOA` use is a bit strange, Cocoa is really just a friendly name encapsulating the framework trio Foundation, AppKit and CoreData and of course, AppKit is _only_ available on OS X. Technically, tvOS doesn't run CocoaTouch either since it is largely minus touch. How about `CINDER_DARWIN` for all the [Darwin](https://en.m.wikipedia.org/wiki/Darwin_(operating_system))-based platforms and `CINDER_UIKIT` for iOS and tvOS?

**Comment by pizthewiz** [comment]
And for symmetry with the other `CINDER_OSNAME` defines, would `CINDER_OSX` be a better fit than `CINDER_MAC`?

**Comment by andrewfb** [comment]
Part of what we're balancing here is breaking a minimum of code against the ideal names. If we were going to start over, I'd choose `CINDER_OSX` but there's enough existing code that I'd vote for keeping `CINDER_MAC`. Similar in the case of `CINDER_COCOA`. We're proposing breaking `CINDER_WINRT` however in favor of `CINDER_MSW_UNIVERSAL` because there's not much code that relies on that (if any) that's not internal to Cinder.

Not that these are not up for debate, but just this is where Rich and I netted out in our own debates in terms of balancing backwards compatibility and ideal names.

**Comment by pizthewiz** [comment]
Keeping the existing names makes sense if the idea is minimize breaking existing code. Maybe those changes might be more appropriate for the next major version or new names could be introduced and used in new code, though it would be nasty to have multiple defines for one value, so that doesn't seem like a great idea either.

**Comment by richardeakin** [comment]
> And for symmetry with the other CINDER_OSNAME defines, would CINDER_OSX be a better fit than CINDER_MAC?

If I recall correctly, we went with `CINDER_MAC` because at the time of its introduction, we were refactoring the app:: stuff and decided AppMac was a clearer choice for the OSX desktop app rather than AppCocoa, which was too similar to AppCocoaTouch. At the same time, AppOsx is odd for obviously reasons, so AppMac and CINDER_MAC is where we landed.

But other than that, and along the lines of what Andrew said, we'd like to make as few breaking changes as possible until we hit another major release. With the proposed changes here we should be good for the foreseeable future and existing projects will work the same.

**Comment by richardeakin** [comment]
I believe this was mostly accomplished with #1430, @andrewfb is it complete? Not sure if there were other adjustments discussed that we'll make (like `CINDER_IOS` / `CINDER_TVOS`).

**Comment by kitschpatrol** [comment]
Minor quip: Now that Apple has announced the transition from "Mac OS X" to "macOS", would it make sense to use CINDER_MACOS instead of CINDER_MAC, to better align with CINDER_IOS and CINDER_TVOS? More verbose, but more consistent with the "CINDER_*OS" template.

**Comment by richardeakin** [comment]
@kitschpatrol unless we were okay with breaking lots of code, we'd have to still define `CINDER_MAC`.

**Comment by richardeakin** [comment]
Just a note that updating WinRT -> UWP macros is still to-do.

**Comment by richardeakin** [comment]
Also when doing the UWP updates, should we renamed vc2015_winrt -> vc2015_uwp? For both cinder.vcxproj and the tinderbox templates

**Comment by richardeakin** [comment]
Discussed offline, the platform macros are all in order for now, and we'll hold off on the VS project file updates until next release so we can do all that in one shebang.
