### ISSUE TITLE
About Cinder Vulkan Android support..

### ISSUE THREAD

**Issue by oscarbg** [cinder/Cinder#1385]
Just seen Fish tornado demo on Google session at GDC today..
so just asking if Cinder Vulkan branch has already Android support or Google has worked on its own..

**Comment by chaoticbob** [comment]
Hi Oscar,

Cinder Vulkan does indeed work on Android...and "technically" Google has worked on it since they are my employer. If you look at the code in ci::vk in the Vulkan branch, you'll see a Google copyright in there. We're currently working to line up the release of Android support in Cinder Vulkan once official support comes to the platform.
