### ISSUE TITLE
Remove _d suffix from libcinder binaries, using folder structure instead

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1429]
If we move away from using the `_d` suffix for debug builds, like in `cinder_d.lib` / `libcinder_d.a`, and instead using paths like `Debug/cinder.lib` and `Release/cinder.lib`,  build configurations (Visual Studio projects, xcode, and cmake) will become a little more maintainable, for example you'll be able to set the linked libraries to the same value for all configurations using a `CONFIGURATION` macro to determine the correct path.

The downside is that it will break existing projects, which will have to update their configuration to point to something like `${CINDER_PATH}/lib/${PLATFORM_TARGET}/$(CONFIGURATION}/cinder.lib`.

There's already going to be some project path breakage when #1307 is completed, so we'll make this change around the same time.

**Comment by richardeakin** [comment]
At a similar time, I'd like to make an adjustment to the VS output directories, so that it is easier to clean up afterwards when you want to do a complete wipe. I've been using the following in other recent projects:

Output Directory: `$(ProjectDir)\build\$(Platform)\$(Configuration)\`
Intermediate Directory: `$(ProjectDir)\build\intermediate\$(Platform)\$(Configuration)\`

So everything ends up in a folder called `build` (which is already how its done with Xcode).

**Comment by vinjn** [comment]
I love the idea of `build` folder.

**Comment by chaoticbob** [comment]
I think the remove of the _d will also make Android and Linux easier as well. I think there's still a few loose ends on Android and Linux where we still have to do the add manually. Linux (and maybe Android) already do the pathed Debug/Release. Would be nice to stick them into a build folder.

FWIW: The reason the build scripts on Linux and Android is called cibuild instead of build was to leave room for a build directory. The initial versions of the build systems did have a build directory, can't remember why it was removed.

**Comment by richardeakin** [comment]
Closed by #1561
