### ISSUE TITLE
cmake and propagating compiler flags (ex. "-std=c++11")

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1504]
This is a two part issue around how we're propagating compiler flags from libcinder target to app targets:

1) Should we be exporting libcinder's `target_compile_options()` as `PUBLIC` ([here](https://github.com/cinder/Cinder/blob/7089c6790383276cd7d10888d018657bae7b6519/proj/cmake/libcinder_target.cmake#L42))? My understanding is that `INTERFACE` won't add the compile options to libcinder itself, just dependencies, but we need to be compiling libcinder with C++11 / 14 as well.

2) Should the `ci_make_app()` macro be including these compile options via the exported `CINDER_INCLUDE_DIRS`?

As a corollary to 2), once we add cinderblock support to `ci_make_app()`, do we want to be adding the dependent target includes for each block as well?

Pinging @PetrosKataras, @gaborpapp.

**Comment by PetrosKataras** [comment]
1) Usually that is the case ( at least for `target_include_directories` and `target_link_libraries` ) but for `target_compile_options` it seems that although specified through `INTERFACE` there are still passed in when building Cinder itself which is why it was not noticed so far. Not sure why this is but we can either way change it to `PUBLIC` since this would be, indeed, closer to the intention.

2) `CINDER_INCLUDE_DIRS` has nothing to do with compile options and its just for specifying include directories so I am not sure what you mean exactly here. The compile options are already forwarded to any application linking to Cinder through the ` INTERFACE_COMPILE_OPTIONS` property as a result of 1). This is one of the main reasons we use and prefer all `target_*` ( e.g `target_include_directories`, `target_compile_options` etc. ) variants instead of the older versions ( e.g `include_directories`, `add_compile_options`, etc. ). More general info regarding these concepts can be found [here](https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#transitive-usage-requirements) .

**Comment by richardeakin** [comment]
Thanks for the responses.

I actually tried for 1) and hit a snag on OS X - it seems that `target_compile_options()` affects ObjC files as well, which can't handle the `-std=C++14` flag. I don't see any way around it, to target only C++ files with `target_compile_options()` (everything I've read says you should set the `CXX_FLAGS` var for this and that doesn't have a `target_*` equivalent).

You cleared up my misunderstanding for 2 offline, I didn't realize that the target picked up the includes automatically when you link to it.

**Comment by richardeakin** [comment]
As I found out in https://github.com/cinder/Cinder/pull/1535, the way to do 1) is with generator expressions, but unfortunately I had to [revert that](https://github.com/cinder/Cinder/pull/1543) because `COMPILE_LANGUAGE:lang` isn't available until cmake v3.3 while our minimum required is currently 3.0. Closing for now..
