### ISSUE TITLE
OSC ReceiverTcp: add endpoint to SocketTransportErrorFn

### ISSUE THREAD

**Issue by patrickFuerst** [cinder/Cinder#1521]
When getting a connection error I wanna be able to access the IP address of the endpoint in my callback, set with `setSocketTransportErrorFn`. 

Is there any reason the endpoint is not passed along in `handleSocketError` found [here](https://github.com/cinder/Cinder/blob/583e67cc41efc7cb68c6769108ff6baa9c13e12f/blocks/OSC/src/Osc.cpp#L1622) ? 

If not I'm happy to make a PR.

**Comment by ryanbartley** [comment]
The design is such that if you want this extra information, you should connect a function to the receiver's [`setOnConnectFn`](https://github.com/cinder/Cinder/blob/583e67cc41efc7cb68c6769108ff6baa9c13e12f/blocks/OSC/src/Osc.cpp#L1070). Then when you get a connection, you can cache a unique identifier with any info related to that connection, i.e. address or socket for advanced cases, such that if you receive an error, you'll know which connection the error happened on and you can choose what to do for that error.

**Comment by patrickFuerst** [comment]
Hey Ryan, 

thanks for the answer. I think you meant [setOnAcceptFn](https://github.com/cinder/Cinder/blob/583e67cc41efc7cb68c6769108ff6baa9c13e12f/blocks/OSC/src/Osc.cpp#L1534). 
What I want to achieve, is to use the address as key to identify clients and whenever an error occurs use the address to handle this. 
The reason for not using the identifier is to avoid iterating over all clients and find the right one for a specific address. I solved this know by caching the clients in a second map.

**Comment by ryanbartley** [comment]
Right. OnAccept is the right callback to use. And the identifier is unique and should be preferred as the key for any key-value pair of connected clients, as two clients could easily have the same asio::ip::address, which is why I don't supply it. Iterating the connected clients to find that unique id or using it as the key of a map doesn't, to me, seem like a heavy process and would be less problematic than using the ip::address string. I do agree after looking at this that it's weird that I'm passing the endpoint into an internal function and not using it. I have a list of features that I'll be looking at implementing next week when I'm finished with my current job and I'll take a look at that error reporting.

**Comment by patrickFuerst** [comment]
Hey Ryan. 

Thanks for the answer. Yeah the not used endpoint made me think about this, but you have some good point against using it :) 

I think we can close this. I say that the right to handle multiple clients is, as you described.
