### ISSUE TITLE
Fundamental problems with ObjLoader

### ISSUE THREAD

**Issue by IntellectualKitty** [cinder/Cinder#1738]
There are two main problems with Cinder's ObjLoader class.

First, since Wavefront .obj files typically contain multiple materials, each of which requires a separate mesh for proper rendering, the ObjLoader should not be derived from geom::Source.  Instead, the ObjLoader should provide access to an array of geom::Source or TriMesh objects.

Second, the materials in Wavefront .mtl files are rich and complex including, for example, ambient, diffuse, and specular colors and/or texture maps, transparency, bump maps, alpha maps, displacement maps, decal textures, etc.  However, the ObjLoader punts by simply assigning the material's diffuse color to the TriMesh vertices.

For reference, Wikipedia has a complete guide to Wavefront .obj and .mtl files: https://en.wikipedia.org/wiki/Wavefront_.obj_file

Incidentally, you may want to check out the Open Asset Import Library (Assimp): http://assimp.sourceforge.net

Assimp is an extremely powerful but simple-to-use 3D model importing library supporting a wide variety of modeling formats including these common formats among many others:

- Autodesk ( .fbx )
- Collada ( .dae )
- glTF ( .gltf, .glb )
- Blender 3D ( .blend )
- 3ds Max 3DS ( .3ds )
- 3ds Max ASE ( .ase )
- Wavefront Object ( .obj )
- Industry Foundation Classes (IFC/Step) ( .ifc )
- XGL ( .xgl,.zgl )
- Stanford Polygon Library ( .ply )
- *AutoCAD DXF ( .dxf )
- LightWave ( .lwo )
- LightWave Scene ( .lws )
- Modo ( .lxo )
- Stereolithography ( .stl )
- DirectX X ( .x )
- AC3D ( .ac )
- Milkshape 3D ( .ms3d )
- *TrueSpace ( .cob,.scn )

The complete list of Assimp's supported import formats is available at http://assimp.sourceforge.net/main_features_formats.html

In addition, Assimp provides many powerful options for pre-processing and optimizing meshes: http://www.assimp.org/lib_html/postprocess_8h.html#a64795260b95f5a4b3f3dc1be4f52e410

There is an easy-to-follow tutorial at http://ogldev.atspace.co.uk/www/tutorial22/tutorial22.html

There is another good tutorial at http://www.lighthouse3d.com/cg-topics/code-samples/importing-3d-models-with-assimp/

**Comment by gaborpapp** [comment]
I think the aim of the integrated ObjLoader class is not to provide an overall model loading capability. More like adding the possibility to deal with simple models. There are blocks for Cinder that integrate Assimp. For example https://github.com/num3ric/Cinder-Skinning from @num3ric.

**Comment by richardeakin** [comment]
I think improvements to `ci::ObjLoader` would be welcomed, however it remains a nice low-dependency (well, no dependencies) alternative to things like Assimp, which hasn't been shipped due to its size and complexity.

I think having ObjLoader load multiple `geom::Source`s is worth thinking about, however thinking about it feels like a bit like a rabbit hole, leading to Collada, which I think at this time no one thinks is a great idea.  Sometimes it feels ObjLoader is just appropriate for very simple cases (like single model files), although this doesn't mean other things can't be improved, like the material support.

Also wanted to point out that @ryanbartley has been working on [glTF](https://github.com/ryanbartley/gltf) support for cinder, which is a much nicer spec as opposed to collada, and also quite lightweight. I know others have been working on support for FBX, though nothing public there yet.

**Comment by IntellectualKitty** [comment]
I ultimately decided to implement an Assimp loader, so this a non-issue.

**Comment by paulhoux** [comment]
For what it's worth: by using Assimp as a DLL, the total size of the Win32 library is slightly over 3MB.

**Comment by thewoz** [comment]
Why the word done by @ryanbartley for the glTF is not yet included officially in cinder?

**Comment by richardeakin** [comment]
ObjLoader is just a simple, basic loader, so it is fairly trivial to maintain it in core. glTF would take more work as it is a much more complex spec and is rapidly changing. With proper support I think it could be done, and is more or less the current plan, but in the meantime I would suggest using Ryan's glTF in cinderblock form and reporting any issues (and successes!) that come up using it.

**Comment by thewoz** [comment]
thanks I understand.
it's just that I have problems with objLoader.
I need to load different models with textures and render it with directional light and shadow.
