### ISSUE TITLE
Support stock Ubuntu14.04

### ISSUE THREAD

**Issue by MikeGitb** [cinder/Cinder#1767]
From the travis file I decern that you are aiming at supporting Ubuntu 14.04 (Trusty Tahr). If so, I would suggest to also target the default tool versions that are found there. Namely

 - CMake 2.8 (currently cmake files state 3.0 as minimal required version)
 - g++-4.8 (the travis file specifies 4.9)

A quick check with current master on XUbuntu 14.04 as well as the Ubuntu version inside WSL seems to indicate that libcinder can be compiled on Ubuntu14.04 with the default tools, but I get a segmentation fault when running the BasicApp example (haven't had time to track it down though). So I can't say if supporting Ubuntu 14.04 is just a matter of adapting a few configuration files or if there are any fundamental incompatibilities / bugs that have to be addressed beforehand.

**Comment by andrewfb** [comment]
Hi - I believe the docs' Ubuntu-specific notes address what you're highlighting: https://libcinder.org/docs/branch/master/guides/linux-notes/index.html 
Do those work for you?

**Comment by MikeGitb** [comment]
@andrewfb: Yes, I am able to compile master as is according to those manuals (actually I used the wiki here at github). 

My points are that 
 - I see no reason to require cmake 3.0 in the first place, IF cinder also works with cmake 2.8 which is the default on Ubuntu 14.04. (I haven't checked if the build system uses any cmake 3.0 features on other platforms)
 - The continuous integration checks the code with g++4.9 whereas on Ubuntu14.04, cinder will most likely be compiled with g++4.8 (which is missing some c++11 features).

**Comment by richardeakin** [comment]
The largest reason I'd vote for keeping those as min requirements are that we're very close to a release, right now the plan is that the only modifications should be docs or bug fixes. Reducing requirements would (at least should) involve more thorough testing, ideally in the field. On top of that, we want to move to at least cmake 3.3 when we can (is available across the board via apt), as well as GCC 5+. As I'm told, the current recommendation on Ubuntu 14.04 is to use clang, anyway, although I'm not sure if that made it into any form of docs.

Concerning Travis, the main reason why we're targeting 14.04 is because that's all they provide on their VM images, unless we go down the windy docker path. We also need 14.04 if we want AWS or TK1 support. Though if you're on desktop, I would think you would want a modern distro given the rapid pace of C++ evolution we're seeing.

If you're using g++4.8 and getting a segmentation fault, it might be due to using the boost binaries that we're currently shipping. There is an option to use the system provided versions (` -DCINDER_BOOST_USE_SYSTEM=1`), whose ABI should match the older compiler.

**Comment by MikeGitb** [comment]
@richardeakin: The recommendation to use clang is new to me (although I use it myself quite frequently) but gcc is definetively the default compiler and even when switching to clang you get still the same libstdc++ version which is missing some c++11 features. I admittedly don't know what travis does in that regard, when you choose gcc4.9

If you are planning to switch to newer versions in the near future anyway, then of course this point is moot.

> Though if you're on desktop, I would think you would want a modern distro given the rapid pace of C++ evolution we're seeing.

Sure, but unfortunately ubuntu 14.04 is still pretty widespread (especailly in centrally adminnistrated environments, where you can't just install newer versions). Personally, I'm using Windows and Ubuntu16.04, so I'm fine with upgrading. I just wanted to point out what I percieved as an unnecessary descepancy

**Comment by andrewfb** [comment]
@MikeGitb separate from the requirements discussion, are you still getting a segfault with BasicApp? If so, I'd be curious to see a gdb backtrace.

**Comment by MikeGitb** [comment]
@andrewfb: No, it works with the flag provided by richard

**Comment by richardeakin** [comment]
> Sure, but unfortunately ubuntu 14.04 is still pretty widespread (especially in centrally administrated environments, where you can't just install newer versions). Personally, I'm using Windows and Ubuntu16.04, so I'm fine with upgrading. I just wanted to point out what I perceived as an unnecessary discrepancy.

Very valid points, really a matter of timing / testing to me.  I also think that with the older linux distros, we can get away with requirements as long as they are available via apt, which you're already going to need to use anyway.
