### ISSUE TITLE
Platform independent windowing and input support -- including Linux -- with SDL

### ISSUE THREAD

**Issue by IntellectualKitty** [cinder/Cinder#1788]
Currently, GLFW is being used to provide support for Linux.  However, [SDL](https://www.libsdl.org) is a more mature and thoroughly developed windowing and input library that supports macOS, Windows, Linux, iOS, and Android (which, I believe, is the same list that Cinder supports) with a 19 year history that is actively maintained, and that also has the support of [Valve Software](http://valvesoftware.com).

Using SDL as the basis for Cinder's App-based classes would have a number of benefits:

1. Separate platform-specific implementations -- including Linux that is currently underway -- would be unnecessary.
2. A smaller and simpler codebase would be required in Cinder.
3. Bug reports from a much wider audience for platform-specific errors that can be difficult to track down and support for those problems from a highly-experience team focused on those issues.

Additionally, SDL supports both joysticks and gamepads, which could easily be incorporated into Cinder.  In issue #1775, I suggested that using GLFW for macOS and Windows would be beneficial because of the builtin joystick support.  However, while I love the clean interface that GLFW has (and have contributed to that project), SDL is a far better choice because (1) it supports all of Cinder's targeted platforms, (2) it is a more mature and complete library, and (3) it has more team and financial resources supporting it.

EDIT: I should also add that I have significant experience with both GLFW and SDL.

EDIT 2: I should also clarify that I still try to contribute to the GLFW project.  All other things being equal, I prefer GLFW hands down.  But I still feel that SDL would be a better fit for Cinder since GLFW doesn't support tablets and because of some of the issues that I've seen in the Linux port where GLFW didn't seem to provide all of the functionality that Cinder requires.

**Comment by richardeakin** [comment]
There has been much thought put into this topic and the conclusion has always been that frameworks like SDL, SFML, Qt, wxWidgets, etc., in general run parallel to cinder, which aims to have as few third party dependencies as possible.  Not having the extra layer between us and the OS X or Windows specific APIs allows us to do some pretty advanced stuff with fewer workarounds. One could argue, and has been argued in the past, that GLFW also falls into the same category as above, and instead for Linux we should directly interface with the X Windowing system. This was considered (and even implemented at one time, IIRC), however with the manner in which Linux distros evolve in somewhat dispersed communities that rely on different backends, and with the advent of Mir and Wayland, it was decided that the only way for us to add Linux support in a maintainable way was with a light third-party abstraction of these various windowing APIs. GLFW is the lightest of the frameworks that provides this, and indeed we ship our own copy of it so we can make modifications when necessary.

Concerning joystick / gamepad support on Mac OS X, the cinder philosophy would be to implement it using platform-specific APIs directly. We're open to using GLFW on OS X and Windows in the future, however this would not be used by default, and would not take priority over directly using Windows / OS X APIs.

Hope that clears up the current views on the topic..

**Comment by vinjn** [comment]
Haha, I think that's one of the biggest difference between Cinder and other creative coding frameworks.

**Comment by IntellectualKitty** [comment]
`Not having the extra layer between us and the OS X or Windows specific APIs allows us to do some pretty advanced stuff with fewer workarounds.`

I am surprised to hear that.  Nevertheless, I have noticed that Cinder Apps have some power management functionality that I haven't seen elsewhere.

In general, my thinking is that there is a lot of value in using high-quality 3rd party platform-independent windowing and input libraries – like GLFW or SDL – because of the wider audience they support.  Platform-specific code is intensive and not infrequently error prone and made more complicated because operating systems and their APIs are constantly changing.  As a macOS guy, I have to say that words like "infamous" and even "nefarious" come to mind with the changes that Apple makes to its APIs as a matter of course – my personal favorite is when they spontaneously deprecate functionality without offering any kind of suitable replacement.

There's a good story about pin-making I once heard about how before modern industrial practices were used, a worker could make only five or six pins a day.  When they started dividing up and focusing the labor – e.g., a worker would have a single, specific job such as fashioning the heads (instead of making the whole pin) – a single worker would be able to contribute to the manufacture of a thousand pins a day.

Computer graphics is intensive work and eliminating the need to do platform-specific coding through the use of existing, high-quality libraries, is beneficial not only because you can benefit from the experience and expertise of people who focus exclusively on that area but even more importantly because it frees up your team to focus on graphics and adding value in your specific arena.

With regard to joysticks and gamepads, I think this is an important feature that Cinder has overlooked since it narrows your audience by ignoring game developers.  Joystick and gamepad support is mandatory for the majority of game developers, and that is a powerful and dedicated audience (which is why I first raised this issue with regard to the ongoing GLFW development).

It is not my intention to waste the time of the Cinder team.   I only brought this up because I thought it would be beneficial, but since you already have other concerns, I'll close both of these issues.

**Comment by richardeakin** [comment]
> There's a good story about pin-making I once heard about how before modern industrial practices were used, a worker could make only five or six pins a day. When they started dividing up and focusing the labor – e.g., a worker would have a single, specific job such as fashioning the heads (instead of making the whole pin) – a single worker would be able to contribute to the manufacture of a thousand pins a day.

https://libcinder.org/gallery

Not pins. :)

**Comment by IntellectualKitty** [comment]
@richardeakin I hope we're not talking past each other.

My point is that if the Cinder team was free to spend their time exclusively on graphics rather than on operating system-specific issues like windowing and input, there would be even more fine projects in the gallery.

The real value and sole purpose of a library like SDL is that it gives you the freedom to do the things that you really want to do – and are uniquely good at – rather than getting bogged down in the same basic operating system code that literally everybody has to do.  It's about not reinventing the wheel.  When I look at the recent history of Cinder commits, more than half seem to be dedicated to operating system issues (that are similar to the issues that I know SDL and GLFW already deal with) and less than half are focused on graphics.

You've stated that "not having the extra layer between us and the OS X or Windows specific APIs allows us to do some pretty advanced stuff with fewer workarounds."  Unless you're planning to have different behavior on different platforms – which I would be awfully surprised by – you're actually looking for consistent cross-platform functionality.  That is what SDL is designed to do, and they don't tout that fact that SDL is used in "Valve's award winning catalog [of popular games]" because they aim to do a poor job of it.

SDL's goal – and the goal of every one of their many, many users – is to provide a highly-functional and consistent cross-platform basis for creating advanced, high-performing projects.  So, if there are things that you need that SDL doesn't already provide, the list likely to be pretty small.  The SDL team is very responsive to bug reports and they welcome patches.  So, if you're already doing something special that they are not, they would most likely welcome the new functionality.

In my book, that's a win for everyone.  You win by being able to spend more of your time on your area of expertise – and expand Cinder's impressive gallery of projects even further – and SDL wins by being able to fulfill more needs.  And you also win by having a dedicated team handling operating system issues fielding bug reports from far more users and far more platforms than Cinder is currently deployed on.

And, frankly, that latter point is pretty important.  After several crashes in the samples when I was first checking out Cinder, I moved on because I felt it wasn't reliable.  I only came back because, after finishing my examination of other comparable engines, I knew that I would be able to bypass Cinder's App framework using either GLFW or SDL, which is how I plan to include joystick support in my project.

**Comment by andrewfb** [comment]
I think most anyone would agree with the points you make regarding the advantages of offloading a portion of the OS-specific code to a 3rd party library, and I appreciate the spirit in which you make them. For what it's worth, I first used SDL over 15 years ago when it was a one-man project of Sam Lantinga's, and I've tracked it since - something I mention only to reassure you that we are indeed aware of it.

You're touching on one of the primary balancing acts we face developing Cinder, which is what burdens are worthwhile for us to take on ourselves, and what are best left to a constituent library. One of the early philosophies guiding Cinder has been to use the host OS as much as possible, as directly as possible, in order to minimize blackboxes, binary size, and the flexibility loss inherent in abstraction. However we try not to be slavishly committed to that for all the good reasons you enumerated above, perhaps the primary of which is to free the finite resource of volunteer manpower to focus on other things.

The recent Linux port has been an interesting test of this philosophy (even more than the partially completed Android port) because of the lack of OS-provided facilities as compared to say, macOS or MSW. With regards to windowing, we decided to use GLFW (and EGL as needed) in part anticipating the additional work that lies ahead with Wayland and Mir. 

In general though we are definitely open to jettisoning our own approaches in favor of someone else's. We did so when moving away from a proprietary math library to GLM, for example. It wasn't without its costs, but I believe it was the right choice. Specifically, while math libraries aren't the same moving target that OS support can be, we liked the fact that GLM was becoming a standard in the GL community, which would allow our users to use examples from books and the Internet directly. Christophe is also actively adding nice features, generally as header-only so users aren't paying for what they aren't using.

A less happy example would be choosing glload for our OpenGL extension management. At the time it was actively developed, and GLEW was not. In retrospect I made the wrong call on that one, and we'll have to remove glload at some point soon in favor of something else. 

Ultimately these decisions will always be an ongoing, multivariate judgment call. It sounds like you disagree with the one we've made so far regarding windowing. That's completely fair, and you've listed reasonable justification, but I wouldn't want you to believe that in making it we haven't been considering the same factors you've cited, as well as others.

It would also not shock me a bit for us to move to SDL or GLFW on all platforms one day, though there's no immediate plans to do so. What is more likely in the interim would be to further abstract the windowing so that it can be selected at runtime. This is another case that Linux is bringing to the fore. As an example, for a current client project of mine, I have cause to use EGL on Linux desktop for a headless cloud rendering application. Facilitating use cases like that, in addition to allowing users who would simply prefer to say, use GLFW or perhaps SDL on platforms other than Linux seems likely for Cinder's near-term future, especially if it's something a few users would like to rally around and collaborate on.
