### ISSUE TITLE
Cinder's built in assertion failure handlers do not use the logging system

### ISSUE THREAD

**Issue by IntellectualKitty** [cinder/Cinder#1804]
The assertion failure handlers implemented in Cinder/CinderAssert.cpp write the assertion failure to std::cerr, but not to the logging system.  If you're running a window-based application without using the console,  the assertion failure is not reported to the user.  Also this makes it appear as if the program has crashed erroneously.

Since log files created with `log::makeLogger<log::LoggerFile>( "/tmp/cinder/cinder.log" )` (code copied from the [Logging in Cinder tutorial](https://libcinder.org/docs/guides/logging/index.html)) appear to be copied to console as well as logged to file, would it be appropriate to use a mechanism similar to the CI_LOG_D macro in place of std::cerr in the assertion failure handlers?

Since the CI_LOG_D macro would log the function signature of the assertion failure handler, this of course is not ideal.  Also, would it be better to add support for an 'assert' log level including a CI_LOG_A macro for general use in assertion handlers?  This might help diagnose programs that choose not to abort when assertions fail as well as programs that do.

**Comment by richardeakin** [comment]
I also think it would be great if the assertion macros were routed to `ci::log` (I think using `LEVEL_FATAL` would be appropriate). I think the only reason why I haven't added it in cinder core is because you'd currently end up with two sets of function meta-data - the one provided by assert itself, and the meaningless one captured in CinderAssert.cpp. I've proposed to some to add a new set of log macros in the form of `CI_LOG_I_RAW()`, `CI_LOG_E_RAW()`, etc, which would not write any extra meta data other than the message yet still route through `ci::log::LogManager` and friends.

There are some subtleties to work through in this, and also lots of debate on how we're going to implement custom metadata formatting, which are just two of the reasons this has been put off. Though if it seems important enough for reliably detecting assertion failures, perhaps we should just use `CI_LOG_F` within the default macros now, and deal with the extra set of meaningless meta data until we have time to fix that appropriately.
 
By the way I say 'I haven't added it to cinder core' because on client projects that I work on, I do indeed override the default assertion macros and use app-specific ones that route the assertion failures to log files.

**Comment by drewish** [comment]
Seeing the duplicated meta data would be a nice reminder to fix that issue ;)

**Comment by IntellectualKitty** [comment]
@richardeakin the issues you mentioned about the logging system became very apparent after I implemented assertion handlers using `CI_LOG_D` (but now that you point it out, `CI_LOG_F` would have been more appropriate).

I agree with you on every point, and I like the design you've proposed.  I think it's important to add this to Cinder's core because Cinder has a very nice logging system and assertion system, and it's unexpected to find that they are not integrated by default.  I've been using the logging system with my window-based application and found it very helpful and have been very happy with it.  So, I was startled when I accidentally triggered an assertion and couldn't figure out what happened.  (I was adding `CI_LOG_D` statements everywhere until I stumbled upon the problem.)

**Comment by richardeakin** [comment]
Reopening as I do find this to be an important issue that we need to address.

Sorry for lack of communication, currently on vacation in far, far away place until next week.

**Comment by IntellectualKitty** [comment]
@richardeakin hope you're having a good time.

In my forked copy of Cinder, I dealt with this just by adding a macro `CI_LOG_A` that plugs into the existing metadata format (and uses the fatal level):

`#define CI_LOG_A( function, file, line, stream )  ::cinder::log::Entry( ::cinder::log::LEVEL_FATAL, ::cinder::log::Location( function, file, line ) ) << stream
`

**Comment by richardeakin** [comment]
Ah, of course that is a very nice solution. In fact, I think we can just instanciate a `ci::log::Entry` directly from within CinderAssert.cpp and skip using the macros there, plugging in the file / line / function info passed in through the assertion macro.

I'm half way through making this change locally, will try to get it finished soon. Need to add a new method for `assertionFailedAbort()` (currently we're just calling the standard library `abort()`, which won't get routed to logs).

**Comment by IntellectualKitty** [comment]
That all sounds good.  What are your thoughts on keeping the macro for cases where assertion handlers are provided by the user?

**Comment by IntellectualKitty** [comment]
@richardeakin this is a bit off topic, but I was thinking about other cases for user-provided assertion handlers (and a possible reason to retain a `CI_LOG_A` macro), and I was wondering what you thought about an assertion handler that put up a message box before aborting the application?  I used that mechanism in a previous project, and the nice thing about it was the convenience since you went directly from problem to code.  In that sense, I think a perfect solution (when not dropping into the debugger) is to both put up a message box and log the assertion failure since you can go directly to code in the simple cases but you can also refer to the log file for problems that require more detailed analysis.

Like you said, it's a better solution to log directly from CinderAssert.cpp rather than to provide a macro.  So, a macro would only make sense for supporting user-defined assertions handlers.  I think logging an assertion failure is beneficial in every case since it's often helpful to be able to refer back to the log file or use it to gather additional information.  But apart from mandatory logging (which I think is automatically disabled if the user doesn't open a log file), there are only a limited number of other things that I can think of doing in an assertion handler: entering the debugger, aborting, putting up a message box and then aborting, and sending an e-mail or text message and then aborting.  However, sending an e-mail or text message seems rather extreme for developing a graphics application unless you're doing some type of fairly serious long-term or distributed testing (in which case attaching the log file to the e-mail might also be beneficial).

So, I was wondering if you had any other thoughts about possible use cases for user-defined assertions handlers.  Customizable assertion handlers is a nice feature, in which case a `CI_LOG_A` macro may be beneficial.  On the other hand, if Cinder already included the complete range of assertion handlers that are useful for developing a graphics application, then customizable assertion handlers (and an assertion logging macro) would be unnecessary.

**Comment by richardeakin** [comment]
> What are your thoughts on keeping the macro for cases where assertion handlers are provided by the user?

Well the macros are sort of for convenience, so you don't need to make a bunch of `ci::log::Entry`s that pass in the metadata all over your app. But for custom assertion handlers, they are just one place, and I think it is pretty nice to be explicit what you're doing there. Also, if we were to add them as macros in cinder/Log.h,h, it wouldn't seem complete without matching all the other levels, which seems a bit heavy to me. I'm still thinking about adding another set as described above, the `LOG_X_RAW()` variations.

Re message-box assertion handler: I know of at least one other person who has added this, however it was windows only fairly difficult to make it cross platform. I suggested at the time that they use the `CI_ENABLE_ASSERT_HANDLER` mechanism for this to add it to their own app.

As far as the ideal solution, I'm not a big fan of putting up a message box; in debug mode mode I'd like it to break directly at the place that the assertion failed, and in release / deploy I would like the app to just crash (since the error is fatal), letting our monitoring software bring it back up as quickly as possible.  Showing a dialog means something the user has to interact with, tell them they did something wrong, and make them worry about.  Some people might prefer a dialog in deploy mode for their application, but I think it is a bit heavy handed to add to the core assertion handlers as it is unclear how to do this in a cross platform manner. Should be straightforward dong it for just windows in a custom handler, though, which could make a nice little cinderblock.

In all cases, I do think we need to write to the log, it is crucial in diagnosing the problem afterwards.

**Comment by IntellectualKitty** [comment]
I don't have programming experience on Windows, but message boxes are very easy on macOS (and I assume the mechanism is similar on iOS).  However, I know that they are very difficult on Linux.  GLFW does not include them for that reason, and SDL implements them with a fairly sizable amount of custom X11 code.

**Comment by richardeakin** [comment]
Fixed in #1829.
