### ISSUE TITLE
Modifications in included 3rd party libraries

### ISSUE THREAD

**Issue by MikeGitb** [cinder/Cinder#1812]
What is the best way to find out which of the third party libraries included in cinder are unmodified copies and which have been adapted?

**Comment by richardeakin** [comment]
Probably the git history. Speaking for myself, I usually commit the third party source first, untouched, then add modifications afterwards. Things might get murky when we update versions..

Also, questions like these are good for the [forum](http://discourse.libcinder.org/), since they aren't an issue per se.
