### ISSUE TITLE
SIGABRT trying to use Audio Unit kAudioUnitSubType_MatrixReverb

### ISSUE THREAD

**Issue by heisters** [cinder/Cinder#1861]
I'm getting a SIGABRT when trying to use ci::audio::cocoa::EffectAudioUnitNode with kAudioUnitSubType_MatrixReverb:

```
Assertion failed: (status == noErr), function setAudioUnitParam, file ../../include/cinder/audio/cocoa/CinderCoreAudio.h, line 155.
```

Here is my setup code, based on the EffectsAudioUnitTestApp:

```
mGain = ctx->makeNode( new audio::GainNode );
mFXReverb = ctx->makeNode( new EffectAudioUnitNode( kAudioUnitSubType_MatrixReverb ) );

mFXReverb >> mGain >> ctx->getOutput();
```

If I swap in a low pass filter, it works. I've tried setting all the parameters on `mFXReverb`, but that doesn't help. Neither does swapping the connection order.

I also tried testing using the EffectsAudioUnitTestApp, but that doesn't build because the cinder.xcodeproj it depends on is missing project.pbxproj.

I'm on the release_v0.9.1 branch, macOS 10.12.5, Mid 2012 MBP Retina.

**Comment by richardeakin** [comment]
I think that kAudioUnitSubType_MatrixReverb is the one with multiple in and out channels? I think that one is a bit more complex to setup than the other audio unit effects, probably doable but I didn't try to figure it out. 

For background information, the original ci::audio design was planning to support platform specific plug-ins, but we later thought better of this because it means fragmentation when you're porting an application to another platform. However the audio unit effects were in there, working, and not harming anything so I left it, although under the caveat that it isn't 'officially' supported (for example, you won't find mention of it anywhere in the audio docs or samples). At this point I'd welcome contributions to facilitate using something like more complex native audio-units, but as for myself I'm committed to a) making sure the low level i / o is working to the highest ability possible and b) building up cross-platform tools that will work on any platform.

To debug your SIGABRT, I'd recommend trying to hunt down what sort of `OSStatus` messages you're getting back where that assertion is firing with a debugger. You'll have to know a fair bit about programming directly with Cocoa Audio Units to get far here, as I imagine you'll need to figure out how to match up all the channel formats.

As an aside, if you just need reverb you might want to look at the [Cinder-STK](https://github.com/richardeakin/Cinder-STK) block, which includes a nice sounding Freeverb wrapper. You can combine that with other effects such as panning and filters to get a pretty decent sounding 3d effect (though obviously not as nice as what many companies are coming out with these days).

**Comment by heisters** [comment]
Thanks for details and debugging guidance. I'll try out Cinder-STK.
