### ISSUE TITLE
Adding Window::getMousePos()

### ISSUE THREAD

**Issue by logixoul** [cinder/Cinder#1929]
App::getMousePos() exists, but it's different from previous versions - it returns coordinates relative to the screen and not to the window. This makes sense now that Cinder is multi-window, but please add a Window::getMousePos() function to get the old behavior.

**Comment by richardeakin** [comment]
I do believe it has been this way ever since cinder added multi-window support, which was 4 or 5 years ago, but I also sympathize with this request - most times I use `App::getMousePos()` on a secondary display I am surprised at the result, even if it is the only display being used. While I think it is a good idea to leave the current functionality intact, adding a new `Window::getMousePos()` method that converts automatically given the window's position seems like a good way to avoid this confusion.
