### ISSUE TITLE
Toolchain Requirements for Linux

### ISSUE THREAD

**Issue by MikeGitb** [cinder/Cinder#1964]
I wanted to extend the build matrix for Linux on Travis CI, and was wondering what toolchains / to versions cinder aims to support.

For example, the cmake files claim to require only  cmake 2.8, Ubuntu 14.04 however comes with 2.8.12, so 2.8 seems overly restrictive. The Travis-CI images come with preinstalled 3.9, and the dependency script installs 3.2. 
The situation with the compilers is similarly unclear. Is gcc supposed to be supported at all? Which version?

**Comment by lucasvickers** [comment]
If I recall correctly, the dependency versions were pulled from our [wiki](https://github.com/cinder/Cinder/wiki), which at the time (and likely still is) the defacto support standard.

We have discussed that we should come up w/ a proper support matrix of linux tooling which would directly correlate with CI.  The challenge is that we are pretty ham-strung by Travis versions.  Since Travis is geared towards web-dev, their recommended method for testing other OS flavors is to use containers.  I investigated this a bit but wound up with compilation errors that were out of the ordinary.

Based on recent experience, I would love to move to an agent based solution such as [buildkite](https://buildkite.com/), but this would require having dedicated machines.

So I know none of this helps you, but hopefully it sheds some light on it.

**Comment by andrewfb** [comment]
We don't have an official baseline for Linux compilers, but it does seem like Ubuntu 14.04 would be appropriate, and consequently GCC 4.8.2 would a nice target. I haven't attempted that recently enough to say with certainty we're still building there however.

**Comment by richardeakin** [comment]
Regarding cmake min version: https://github.com/cinder/Cinder/pull/1877

**Comment by MikeGitb** [comment]
@richard: 
Thanks for the Link. I just remembered that Ubuntu 14.04 has an official cmake 3.5 package: https://packages.ubuntu.com/trusty/devel/cmake3

Also, as I said, the "normal" cmake version is 2.8.12 instead of 2.8, which added some new features, in particular `target_compile_options`.

**Comment by andrewfb** [comment]
If 2.8.12 adds features over 2.8 that we'd benefit from, I imagine we can bump this. Ubuntu 14.04 is what's driving the baseline for us, both on gcc and CMake. Thanks for taking a look at this.

**Comment by MikeGitb** [comment]
`target_compile_options` is already used but I guess as no-one is using cmake <2.8.12  this wasn't a problem.

In any case, my original goal was to understand which configuration should be supported and hence should be part of the ci checks. However, I didn't find a way to downgrade the cmake version on the travis images  so that's a moot point.

Anyway, 
- here is a PR updating the required cmake version to 2.8.12: https://github.com/cinder/Cinder/pull/1970
- and here is a PR updating the build matrix - including a build that uses the default compiler on trusty (g++4.8): https://github.com/cinder/Cinder/pull/1969

**Comment by MikeGitb** [comment]
@andrewfb:

> Ubuntu 14.04 is what's driving the baseline for us

Now that ubuntu18.04.1 is about to be released, have you considered raising this to ubuntu 16.04, which would mean cmake 3.5 and g++-5.

**Comment by richardeakin** [comment]
I think it hinges on the latest supported by travis CI and AWS.

**Comment by MikeGitb** [comment]
I see
FYI: while travis is using trusty, the default versions of cmake, g++ and clang are much newer than what you would find on a regular installation of 14.04.

**Comment by paulhoux** [comment]
Yesterday I tried compiling Cinder on Ubuntu, which wasn't as hard as I thought. You can say I am curious about Linux and Cinder development, not so much for Android but more as a stable platform for installations. 

I followed [these directions](https://www.libcinder.org/docs/guides/linux-notes/ubuntu.html), but I had to make the following changes to make it work:
 * On a clean Ubuntu installation, CMAKE nor CLION were able to find the default compiler. I fixed this by doing `sudo apt-get install build-essentials`.
 * The list of dependencies needs an update. When used as-is, it complained about libraries being obsolete. I followed the recommendations and replace the `-bad` ones with proper ones.

I haven't been able to compile and run a sample yet, but Cinder compiled successfully.

**Comment by paulhoux** [comment]
Not sure what version of Ubuntu it was. I downloaded the stand-alone installer, so I could run Ubuntu from a USB drive. If you can tell me where I can find the version, I'll let you know.

`sudo apt-get install clang` wasn't able to find the package. Adding a version like `clang-3.3` didn't change that. Nor did it help to add LLVM repositories, as explained [here](https://blog.kowalczyk.info/article/k/how-to-install-latest-clang-6.0-on-ubuntu-16.04-xenial-wsl.html).

**Comment by richardeakin** [comment]
FWIW `sudo apt-get install build-essentials` has always been the first thing I do upon setting up a fresh Ubuntu install, so maybe we should update our ubuntu install docs with that recommendation?

**Comment by MikeGitb** [comment]
> If you can tell me where I can find the version, I'll let you know.

    lsb_release -a

> sudo apt-get install clang wasn't able to find the package.

The only thing I can think of is that you have to do a `sudo apt update` that should update th package list and maybe that is also the reason, why you got warnings about deprecated packages. 

In general, I'm not sure, why the recommendation is to install clang in the first place and even make it the default system compiler. Afaik gcc compiles cinder quite well and while I prefer clang too, I certainly wouldn't want the installation of cinder to change my default compiler.

**Comment by lucasvickers** [comment]
Yes the limitations on OS are very much Travis-CI, you can see [here](https://docs.travis-ci.com/user/reference/overview/).  Travis-CI is very much about web development and since most organizations are moving towards containers Travis-CI says you can just containerize a different OS version for your testing.  This is true for web-services, but preliminary tests have shown it to be problematic for running Cinder.

If we had a corporate sponsor and I could do it all over again I'd use [BuildKite](https://buildkite.com/) on a cluster of dedicated machines with different configurations.  The toolchain matrix starts to get unruly tho, but I wonder if there's a creative way we could solve for that.

**Comment by MikeGitb** [comment]
> Yes the limitations on OS are very much Travis-CI, 

As I said before: While the Ubuntu version used by Travis is outdated, the tools running on it are not (except for gcc itself). So imho it doesn't make sense to say "we have to support tool version X because that's what Ubuntu 14.04 brings by default and Travis is using Ubuntu 14.04". 

As you can see [here](https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/), Travis provides cmake 3.9 and clang-5 by default while a vanilla ubuntu14.94 would have cmake 2.8.12 and clang-3.4(?)

**Comment by PetrosKataras** [comment]
I would agree with @MikeGitb on this - There are a few residual things( especially on the Wiki ) from the very early days of the port to Linux, that would need to be updated, removed and/or corrected. 

Most of these things have already been mentioned here ( i.e min CMake version requirement, confusing recommendation about Clang etc. ) and IMO it would be a great time ( now that 18.04 is out ) to try and revise these info and version numbers wherever we can. If Travis provides updated package versions, then my vote would also be to set the min requirements based on that and not on what 14.04 offers by default, which at this time feels quite restrictive.

Regarding Paul's issue with installing packages etc. I would also agree with @MikeGitb in that it was most probably caused by an outdated package lists index which is a common thing, especially on fresh Ubuntu installations, thus the first thing to do after installing the OS, and before trying to install any dependencies, is to run `sudo apt-get update`. You can actually see Travis failing currently because of this here https://travis-ci.org/cinder/Cinder/jobs/407804827#L475-L501.

Personally, I tried Cinder on 18.04 the first days of the release and compiled without any issues and without any mods required, with both gcc and Clang.

**Comment by MikeGitb** [comment]
Does anyone know,  on what systems and with what compilers cinder is commonly used?

**Comment by MikeGitb** [comment]
At least my original question has been discussed and resolved in https://github.com/cinder/Cinder/issues/2142 (particularly https://github.com/cinder/Cinder/issues/2142#issuecomment-668330563): 

Min CMake: 3.10
Min Ubuntu: 18.04

There should probably be a separate issue about updating the wiki with the new requirements.

Also relevant: https://github.com/cinder/Cinder/pull/2199
