### ISSUE TITLE
Serial support not built for Mac OS

### ISSUE THREAD

**Issue by oqu** [cinder/Cinder#2152]
Hi,

I am trying to build a project that has a dependency to cinder and its serial class.
I noticed Serial.cpp was not built for Mac OS:
https://github.com/cinder/Cinder/blob/26c958b6d897e1a56731b4703025b6d49ece995c/proj/cmake/libcinder_source_files.cmake#L72

Maybe this
```cmake
if( ( NOT CINDER_LINUX ) AND ( NOT CINDER_ANDROID ) )
	list( APPEND SRC_SET_CINDER
		${CINDER_SRC_DIR}/cinder/Capture.cpp
	)
elseif( NOT CINDER_ANDROID )
	list( APPEND SRC_SET_CINDER
		${CINDER_SRC_DIR}/cinder/Serial.cpp
	)
endif()
```
should be replaced by
```make
if( ( NOT CINDER_LINUX ) AND ( NOT CINDER_ANDROID ) )
	list( APPEND SRC_SET_CINDER
		${CINDER_SRC_DIR}/cinder/Capture.cpp
	)
endif()
if( NOT CINDER_ANDROID )
	list( APPEND SRC_SET_CINDER
		${CINDER_SRC_DIR}/cinder/Serial.cpp
	)
endif()
```

What do you think ?

**Comment by richardeakin** [comment]
I believe you're right, that logic to add Serial.cpp looks wrong to me. AFAIK it should be available on all platforms except Android and iOS (the define we've been using for that is `CINDER_COCOA_TOUCH`).

Would you be able to submit a pull request to fix this? Otherwise, there are a lot of cmake things to look at and I hope to be able to help with that when I have the time (not sure yet when that will be..).
