### ISSUE TITLE
Educate TinderBox about architectures / ANGLE

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#680]

**Comment by richardeakin** [comment]
Is this completed?

**Comment by andrewfb** [comment]
This is as complete as we'll likely pursue in 0.9.0. I haven't really attempted a design for multi-architecture CinderBlocks yet and intend to let the dust settle on all our platforms before doing so. Closing for now.

**Comment by pizthewiz** [comment]
This isn't a big deal for OS X or iOS, but leaves Windows in a tighter spot since it doesn't support a fat binary format. As such, stuff like the Oculus Rift SDK has to provide separate libs for `win32` and `x64` and in turn the [CinderOculusDK2 CinderBlock](https://github.com/jhurlbut/CinderOculusDK2) has to choose which of two architectures it supports.

[https://github.com/jhurlbut/CinderOculusDK2/blob/master/cinderblock.xml](https://github.com/jhurlbut/CinderOculusDK2/blob/master/cinderblock.xml):
```xml
<platform os="msw">
    <!--
      without an arch attribute we cannot support Win32 and x64 with the same block, see:
        https://forum.libcinder.org/topic/cinder-block-xml-specify-architecture
    -->
    <platform config="debug" compiler="vc2012">
        <staticLibrary>lib/LibOVR/Lib/Win32/VS2012/libovrd.lib</staticLibrary>
    </platform>
    <platform config="release" compiler="vc2012">
        <staticLibrary>lib/LibOVR/Lib/Win32/VS2012/libovr.lib</staticLibrary>
    </platform>
    <platform config="debug" compiler="vc2013">
        <staticLibrary>lib/LibOVR/Lib/Win32/VS2013/libovrd.lib</staticLibrary>
    </platform>
    <platform config="release" compiler="vc2013">
        <staticLibrary>lib/LibOVR/Lib/Win32/VS2013/libovr.lib</staticLibrary>
    </platform>
    <staticLibrary absolute="true">Winmm.lib</staticLibrary>
</platform>
```

Would `x64` make a more sane default for Windows?

**Comment by pizthewiz** [comment]
Interesting, the [Cinder-OculusRift](https://github.com/num3ric/Cinder-OculusRift) block makes use of `$(PlatformTarget)` which seems to be the architecture.

[https://github.com/num3ric/Cinder-OculusRift/blob/master/cinderblock.xml](https://github.com/num3ric/Cinder-OculusRift/blob/master/cinderblock.xml):
```xml
<platform os="msw">
	<platform config="debug">
		<staticLibrary absolute="true">winmm.lib</staticLibrary>
		<staticLibrary>LibOVR/Lib/$(PlatformTarget)/VS2013/libovrd.lib</staticLibrary>
	</platform>
	<platform config="release">
		<staticLibrary absolute="true">winmm.lib</staticLibrary>
		<staticLibrary>LibOVR/Lib/$(PlatformTarget)/VS2013/libovr.lib</staticLibrary>
	</platform>
</platform>
```

**Comment by andrewfb** [comment]
Yes - I need to revisit all this specifically around techniques like $(PlatformTarget). One option is to have TinderBox parse that out, so that it can make sure the relevant libraries were copied. In general I prefer to use $(PlatformTarget) anyway since it allows you to keep your linker/compiler directories uniform across architectures.
