### ISSUE TITLE
ci::Signal priority is reversed from boost::signals2 priority.

### ISSUE THREAD

**Issue by sansumbrella** [cinder/Cinder#804]
The priority option in boost::signals2 acted kind of like a render layer. Higher numbers were called after lower numbers. The new signals do the reverse: higher numbers are now called before lower numbers. Using the term `priority`, I think the new ordering makes sense. When connecting things like the draw signal, though, it can be confusing.

What's the reasoning for the switch? Should I just learn to live with the new, or might we change it so there is less breaking of existing applications?

**Comment by richardeakin** [comment]
I chose the order this way because it is the same as a [priority queue](http://en.wikipedia.org/wiki/Priority_queue) and I thought it would be easier to remember given the name. We're not concerned with matching what boost does, since it wasn't a 1:1 replacement, but also to me boost::signals2 uses the term 'order' which is harder to reason about (I would get it reveresed quite often). I'm not sure how the usage with connecting the draw signal is confusing, perhaps its just a different way of thinking?

**Comment by sansumbrella** [comment]
In general, I think higher priority going first makes more sense.

For rendering, it feels like layer order, where higher layers are drawn later. So priority as a concept feels backwards for rendering.

Mostly wanted to check in and see what was intended.

**Comment by richardeakin** [comment]
I think good thing I didn't name it 'order' then. :)
