### ISSUE TITLE
no shader unbind function

### ISSUE THREAD

**Issue by jhurlbut** [cinder/Cinder#836]
The unbind function of GlslProg has been removed from glNext. If you use shader->bind without batches then it appears the shader never gets removed from the context causing issues down the render pipeline. If you use shader->bind with popGlslProg() it doesn't seem to unbind the shader properly. The only way that seems to work is to use a combo of pushGlslProg and popGlslProg. If that's the case I would recommend removing the bind function altogether if unbind is removed. The current setup is not very straightforward if you choose to bind shaders directly in glNext.

**Comment by ryanbartley** [comment]
I believe the reason for this is that the pipeline doesn't need the extra null call to glUseProgram, since you always need a shader bound in modern OpenGL. In OpenGL 2.0, you could draw without a shader bound so the unbind call was needed functionally. If you're about to draw something that needs a certain shader, bind it and don't worry about the unbind of the last shader because the call to glUseProgram with the new shader will invalidate the old shader.

**Comment by jhurlbut** [comment]
That's was my initial impression. It appears that Cinder maintains a stack of glslprogs and if this stack is inconsistent with the bind state then bad things happen.

**Comment by ryanbartley** [comment]
It definitely has logic peculiar to Cinder, but to screw up the state inside gl::Context you'd have to do some really weird stuff, specifically calling into vanilla gl. It isn't "consistent" with modern OpenGL because modern OpenGL isn't concerned with how you use the API, it's concerned with allowing you to draw stuff to the screen however you choose. Cinder's OpenGL wrapper is concerned with making your calls to OpenGL the most performative, hence the introduction of a stack. 

The stack is actually a really good thing. Let's say that you have an application that just uses one shader and you bind the shader at the beginning and were able to unbind it at the end. Then you'd have multiple redundant calls to OpenGL because you don't need the unbind call. The driver would then have to synchronize the program state on every draw call, which is costly. Cinder can take out those synchronizations because it can check what the latest state is and decide whether things have changed. If they have, it'll issue the corresponding GL call. If not, then OpenGL can keep everything as it was, performance boost. 

The stack also helps with cleanup. Let's say that you have some complex state in functionA and different complex state in functionB. By using the scoped variables, you can guarantee that state will be reset and reconfigured correctly as long as the scopes are correct.

**Comment by jhurlbut** [comment]
I'm fine with the stack but it seems like functionality that is incompatible with the stack should be removed. Seems like shader->bind is vestigial and leaving a half working implementation will be confusing to more people than just me I would gusess.

**Comment by ryanbartley** [comment]
The bind function isn't incompatible with the stack, it uses the stack. Bind calls [this](https://github.com/cinder/Cinder/blob/glNext/src/cinder/gl/Context.cpp#L811) function, which changes the stack.

**Comment by richardeakin** [comment]
IMO GlslProg in glnext is more congruent than 0.8.6 If you look at the old [GlslProg::unbind()](https://github.com/cinder/Cinder/blob/master/src/cinder/gl/GlslProg.cpp#L117-L120) it is the same as calling `GlslProg::bind( 0 )`, which is pretty typical when you are writing raw gl. So you can still do that if you like. :)

**Comment by pizthewiz** [comment]
Admittedly I ran into the same confusion a few weeks back trying to modernize the Syphon CinderBlock and samples. A comment in [GlslProg.h](https://github.com/cinder/Cinder/blob/glNext/include/cinder/gl/GlslProg.h) might be helpful as that is where I went first.
