### ISSUE TITLE
iOS Window Width/Height inconsistent (MovieWriter funky)

### ISSUE THREAD

**Issue by dscheibel** [cinder/Cinder#886]
I noticed inconsistent window width/height values while working with the MovieWriter Sample on iOS.

(https://github.com/cinder/Cinder/blob/glNext/samples/QuickTimeAvfWriter/src/MovieWriterApp.cpp) 

I'm writing following info to the console
console() << getWindowBounds() << ", " << getWindowCenter() << ", "<< getWindowWidth() << ", "<< getWindowHeight() << endl;

I'm working with an iPhone 6. 
While setup gives me the right numbers. I'm getting wrong values in update and draw.

setup(): (0, 0)-(375, 667), [  187.500,  333.500], 375, 667
update(): (0, 0)-(320, 568), [  160.000,  284.000], 320, 568
draw(): (0, 0)-(320, 568), [  160.000,  284.000], 320, 568

This is a screenshot of the app:
![img_1402](https://cloud.githubusercontent.com/assets/279711/7528736/05e53644-f4fb-11e4-8eab-f22347a0f8f3.jpg)

This is a screenshot of the rendered movie:
![screen shot 2015-05-07 at 8 58 09 pm](https://cloud.githubusercontent.com/assets/279711/7528794/ec495a8e-f4fb-11e4-9fb8-4a5c06590965.png)

Helpful links: 
http://www.paintcodeapp.com/news/iphone-6-screens-demystified

**Comment by dscheibel** [comment]
I also figured out an easy way to copy the video into the photos app to immediatly see the result:
https://forum.libcinder.org/#Topic/23286000002297045

**Comment by andrewfb** [comment]
@pizthewiz does this happen to be something you have insight into / experience with? I was able to repro this on my iPhone 6, and it seems to be related to the new hoop-jumping necessary to use the full resolution on that device. It appears that when layoutSubviews is called ( https://github.com/cinder/Cinder/blob/glNext/src/cinder/app/cocoa/CinderViewCocoaTouch.mm#L81 ) the self.bounds value has been set to (320,568) rather than the device's (375,667)

**Comment by pizthewiz** [comment]
Hmm, I haven't done anything with Cinder on iOS yet, but how is the `CinderViewCocoaTouch` sized to match the device bounds?

**Comment by richardeakin** [comment]
I think I've found a fix for this, it is iOS8 specific. Basically they are now requiring us to add a LauncScreen.xib file ([see here](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LaunchImages.html), please read between the lines as usual) for layout in iOS8+. To me this is actually better than the previous Images.xcassets crap, though I think we'd have to leave that for now in order to support whatever previous OSes needed that.

To test, please run test/iosAppTest in the branch [glNext_ios_windowsize](https://github.com/cinder/Cinder/tree/glNext_ios8_windowsize)

I've only tested this in the iphone 6 simulator. For the record, I was printing `[UIScreen mainScreen] bounds]` and after viewDidAppear it was the wrong size.. to me that indicates the project file needs to be updated to 'go with the flow'.

**Comment by richardeakin** [comment]
Update: glNext_ios_windowsize has been merged into glNext. See #943 for how to update your existing projects. Will leave this issue open until we've updated samples and tinderbox templates.

**Comment by andrewfb** [comment]
In addition to the general Cinder fix, 9e39e3ca6418d8052fd6984d003c7fb417951260 updates this specific sample.
