### ISSUE TITLE
Building for iOS Simulator fails

### ISSUE THREAD

**Issue by wdlindmeier** [cinder/Cinder#944]
Getting these issues when compiling a glNext app for the simulator. It does build successfully for the device.

![screen shot 2015-05-28 at 11 13 22 am](https://cloud.githubusercontent.com/assets/132988/7867467/1e7a5b36-052b-11e5-8c89-b156f81a5aad.png)

Seems to mainly be associated with boost system and filesystem.

**Comment by richardeakin** [comment]
I believe it is because the default project settings are taking over and trying to build the simulator as 64-bit, whereas libcinder_iphone_sim.a is only 32-bit (I think this is good, at least for binary file size reasons).  Try changing Project Settings -> Architectures to `$(ARCHS_STANDARD_32_BIT)` and let us know if that works for you.

**Comment by wdlindmeier** [comment]
That'll do it! Is this something that can be set by Tinderbox?
