### ISSUE TITLE
Crash in RendererImplGlCocoaTouch makeCurrentContext:(bool)force on iPhone5/iOS8 with preprocessor CINDER_GL_ES_3

### ISSUE THREAD

**Issue by yderidde** [cinder/Cinder#959]
I'm currently developing an iOS8 app for GL_ES3.0 I know that the iPhone 5 do not have ES3.0 however currently if you try to run an app on iPhone5 with cinder (with ES3.0 preprocessor), the app is going to crash hard at the AppImplCocoaTouch init. 

**Would be great to handle this case gracefully and avoid crashing the app**
 
In my case, I would like to still be able to run but simply disable the cinder viewport if the device do not have an ES 3.0 enabled GPU...

**Comment by yderidde** [comment]
Stack trace
```
#0	0x0020a2fc in std::__1::vector<int, std::__1::allocator<int> >::empty() const [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:659
#1	0x0020a2fc in bool cinder::gl::Context::setStackState<int>(std::__1::vector<int, std::__1::allocator<int> >&, int) at /MyApp/libs/cinder/src/cinder/gl/Context.cpp:1601
#2	0x0018d79e in cinder::gl::Context::bindFramebuffer(unsigned int, unsigned int) at /MyApp/libs/cinder/src/cinder/gl/Context.cpp:1068
#3	0x001583a2 in -[RendererImplGlCocoaTouch makeCurrentContext:] at /MyApp/libs/cinder/src/cinder/app/cocoa/RendererImplGlCocoaTouch.mm:220
#4	0x00184842 in cinder::app::RendererGl::startDraw() at /MyApp/libs/cinder/src/cinder/app/RendererGl.cpp:158
#5	0x00185c7e in -[CinderViewCocoaTouch makeCurrentContext] at /MyApp/libs/cinder/src/cinder/app/cocoa/CinderViewCocoaTouch.mm:106
#6	0x0017615a in -[AppImplCocoaTouch init:settings:] at /MyApp/libs/cinder/src/cinder/app/cocoa/AppImplCocoaTouch.mm:132
#7	0x0016e318 in cinder::app::AppCocoaTouch::AppCocoaTouch() at /MyApp/libs/cinder/src/cinder/app/cocoa/AppCocoaTouch.cpp:48
#8	0x000fefec in MyApp::MyApp() at /MyApp/src/MyApp.mm:12
#9	0x000feeb0 in MyApp::MyApp() at /MyApp/src/MyApp.mm:12
#10	0x000fe59e in void cinder::app::AppCocoaTouch::main<MyApp>(std::__1::shared_ptr<cinder::app::Renderer> const&, char const*, int, char* const*, std::__1::function<void (cinder::app::AppCocoaTouch::Settings*)> const&) at /MyApp/xcode_ios/../../libs/cinder/include/cinder/app/cocoa/AppCocoaTouch.h:264
#11	0x000fd66e in main at /MyApp/src/MyApp.mm:52
```

**Comment by pizthewiz** [comment]
Hmm, if ES3 support is a compile-time option this might be pretty involved. I believe you can check if the device supports ES3 by checking if the result of the following is `nil`:
```objective-c
EAGLContext *context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3];
```

**Comment by yderidde** [comment]
It actually crash in the constructor of the App .. Way before I can do anything.

**Comment by richardeakin** [comment]
I'm not sure how we'd finish the init process without a valid `RendererGl`.  We could add in an error log + `exit()` function in there so the crash is less scary looking. :)  Seriously, open to options but we need to weigh in whether it is worth it to support the app continuining to load with no renderer so that it can display a black screen.

**Comment by yderidde** [comment]
Well, you also have to consider the scenario where It is an iOS app that starts from a native UIKit view and only show later on the cinder viewport. In that case, you would want to still be able to run but show a black viewport. At least the rest of the app should work as expected.

**Comment by pizthewiz** [comment]
It seems reasonable to want to be able to at least present the user with some info when the context creation fails, especially when Cinder is integrated via custom `UIView`, but I suspect that change would still cut rather deep as a bunch of cinder-internal code paths would need to handle an invalid `RendererGl`.

**Comment by yderidde** [comment]
I understand that it will involve some refactoring but I think it is actually for the better.
I guess it is an architecture flaw of Cinder. The primary focus from what I can see thru the current architecture is to handle standalone 'pure' cinder apps. The integration into third party native apps such as iOS is a second citizen and was added after the fact with some pseudo-clean workarounds.. 
 
A better architecture (just thinking loudly here and may be more of a vision than a fix for now) would be to consider Cinder as a 'module' or as a 'view' within an app .. doesn't matter if it is a win32 c++ or iOS CocoaTouch or Cocoa OSX app .. 
Cinder shouldn't be responsible of bootstrapping the application by imposing its own main app class etc...
Let the developer create their own app project and let the ability to instantiate Cinder whenever it make sense to them .. 
You can think of a class such as "CinderView" that according to the platform will be an NSView (OS X), or a UIView (iOS) or whatever else for other platforms and as a developer i would just instantiate that class with all the necessary options and add it to my own view hierarchy where i need, when i need.

This way, not only i would have more freedom for my app design and bootstrap but in this particular scenario I could test for ES3 and instantiate or not the Cinder View accordingly ... and have my own experience on what to show/do in case ES3 is not enabled on a particular device

**Comment by richardeakin** [comment]
If you're already using a UIView or NSView, there's nothing stopping you from testing for presense of ES3 already.  The current design of `ci::app` is for cross platform applications, you can of course opt out of it entirely and some people do. So far there hasn't been a large enough use case to warrant making `CinderView` more accessible on its own (you currently can, but it is long winded), its a matter of development time budgeting.

Not to say that we can't improve how RendererGl fails when it can't make a gl context.

**Comment by yderidde** [comment]
@richardeakin Can you point me to an example of how to bootstrap cinder without using ci::app ? this would be helpful. :)

**Comment by andrewfb** [comment]
I made a commit a7a0491 which should at least throw an exception when this occurs, rather than crashing outright. Does that help in your use case?

With regards to embedding Cinder without a ci::app, we don't precisely have an example of that. However samples/iosNativeControls might be instructive. Also ultimately CinderViewCocoaTouch is simply a UIView. You might have to do a bit of surgery on Cinder to make it work, but if it's a route you want to pursue I imagine we'd be open to a PR to simplify that path. Also, you can allocate a gl::Context() using an existing EAGLContext if you wanted to go that route, and just use Cinder without the app:: portion.

**Comment by yderidde** [comment]
Thanks ! I'll pull and see how i can use it as is for now until I have time to move to a solution where I bypass ci::app all together.

My project is kinda based on iosNativeControls sample. In fact, because I need to setup push notifications , i had to override app::launch() to be able to pass my own UIApplicationDelegate. I had to duplicate some code from the super implementation. 
Could be very easy to expose a way to pass your own ApplicationDelegate .. it is actually a very common situation and it would actually make sense for the app developer to own that class , its the entry point of many things.

**Comment by richardeakin** [comment]
We can try to support a way for you to hook into push notifications. PR's are most welcome around this, or push some code where we can look at what it would take to enable this functionality.

**Comment by yderidde** [comment]
Well regarding the access to the AppDelegate its all good , i simply override the launch() method, and execute my own app delegate 
::UIApplicationMain( argc, argv, nil, ::NSStringFromClass( [MainAppDelegate class] ) );

**Comment by richardeakin** [comment]
Nice one, though in this case I take it you're pretty much ditching all of the ci::app::App functionality, since it's app delegate is doing important initialization necessary for things like ci::app::Window to work.  Seems like it could be made to work, although I wouldn't mind adding hooks to our app delegate ([AppImplMac](https://github.com/cinder/Cinder/blob/master/include/cinder/app/cocoa/AppImplMac.h#L44) on desktop, the [iOS version](https://github.com/cinder/Cinder/blob/master/src/cinder/app/cocoa/AppImplCocoaTouch.mm#L33-L51) is a little ligher but still crucial), so that the application can remain as cross platform as possible, yet still provide support for the mac / iOS specific  features.

I'm going to close this issue since andrew added a fix for the root of it, and open a new feature issue for supporting platform specific hooks. Still, if you find you can make things more flexible for your workflow in other ways, please let us know.
