### ISSUE TITLE
why don't you guys use dijini from dropbox something like a swig for android and ios

### ISSUE THREAD

**Issue by hamedmohammadi** [cinder/Cinder#984]
you can use you c++ code in android and ios as easy as possible 
https://github.com/dropbox/djinni
see this link it a big and active project from dropbox

**Comment by hamedmohammadi** [comment]
as more details to how to use it a sample template project was created by @skabbes in mx3 
see that 
https://github.com/libmx3/mx3

**Comment by andrewfb** [comment]
Hi - thanks for the suggestion. If someone wants to wrap Cinder up for non-C++ languages they're very welcome to do so, but it's not a priority for the core project for now.

**Comment by hamedmohammadi** [comment]
i saw several requested for porting to android and the answers from core
contributers was its the complexity of porting to both android and ios .
and i like your projects to be port in these platforms .whatever i will
wait for android portion and tnx for your answer

**Comment by richardeakin** [comment]
Well I think dropbox approached the problem of cross-platform abstraction much differently than we do anyway; where they are trying to wrap individual native componenets, such as a tableview or even HashMap vs NSDictionary, we prefer building tools that are fundamentally cross platform (ex. gl::VboMesh), and then exposing and abstracting whatever native functionality is needed (ex. app touch events, or motion sensors). I personally don't think the approach they've taken in djinni scales well at all.

**Comment by skabbes** [comment]
@richardeakin I agree that djinni isn't for everyone - but I wanted to clear up some things, because I think you misunderstand it.

The approach isn't at all to just wrap individual native components. The idea is to allow you to describe an API in a language agnostic way.  If you have a virtual interface in C++, djinni allows you to implement it in either objc, java or c++.  Sure, it also provides json-ish primitives like map, array, int, etc. But those are the building blocks of any API.

If you've ever hand-written JNI code, or objc++ code before, you will appreciate what djinni does, but it very much _not_ a framework.  It is a tool.

While I doubt that you'd use a djinni for your VboMesh (for perf reasons), you could certainly make a nice Java API by simply writing the following in djinni file.
```
# Create an Java / Objc / C++ interface which will be implemented in C++.
gl_vbo_mesh = interface + c {
    bind_all_data();
    buffer_indices(indicies: list<i32_t>);
    // etc.
};
```

In response to "djinni doesn't scale".  Djinni was used successfully on Mailbox (iOS, Android, Mac), Carousel (iOS, Android) and to a lesser extent the Dropbox app itself.  Also recently, Facebook used it to create Facebook Moments. https://code.facebook.com/posts/498597036962415/

You are surely entitled to your own opinion on how to build cross platform applications, but I just wanted to clear the air on some of the misconceptions you seemed to have about djinni.

Cheers.

**Comment by richardeakin** [comment]
Not a bad defense. :)  I'll admit that 'doesn't scale well at all' is a bit harsh on my part, maybe that is better said as 'doesn't scale where we need it to.'  Probably the largest difference is between the platforms that dropbox targets (typically 'apps' for an app store), and those that cinder targets (sometimes 'apps', many times installations, hopefully almost always unusual).

What I took from [your cpp con talk](https://www.youtube.com/watch?v=5AZMEm3rZ2Y) on writing Dropbox was that you guys were looking to access native UI components from a cross-platform interface, example being a scrolling tableview with data sources.  This works with your currently targeted platforms, but what if you need to get your code on onto a platform where there just isn't a decent native scrolling tableview, or you just don't like the one that platform provides?  You have to write your native scrolling tableview from scratch and the native abstraction is moot.

To provide a concrete example in the context of cinder, we had to make a similar decision when deciding how to implement cross platform audio. Did we want to abstract Audio Units on mac / iOS, and XAudio on Windows? This would buy us some nice things like reverb and 3d mixing, but what about android? If we use their java based effects we foregoe any C++ audio processing. What about the obvious fact that XAudio2 is bent towards 3d game audio and provides no notion of audio graph, while Audio Units is meant for DAWs and resellable plug-ins, or that the reverb units sound wildly different on each platform? The list of platform-specific differences here can go on and on. Instead we decided to implement the core of our audio toolbox in straight C++, and make use of platform specific constructs for accessing devices and file i/o.  Then if / when we port to android, we get the exact same sounding effects, same 3d tools, consistency.  This is not the choice everyone takes (ex. UE4 uses XAudio2 for its audio back end on windows), but we feel it is the right one for our targeted domains, and worth the work.

I hope this has proved to be a healthy debate, or continues to do so. :)

**Comment by skabbes** [comment]
Ya, I was about to say that probably djinni wasn't built for the typical Cinder use case, and I'm not necessarily arguing that it should be incorporated.  _However_, you are kind of arguing against the way that Dropbox _uses_ djinni, not djinni itself.  Mailbox build a tableview abstraction because we aren't really cross platform, we are multi-platform - iOS, Android, Mac, and hopefully one day Windows & WP7. I suppose Cinder is different here - and needs ultimate flexibility.

I think most people know the Cinder way of doing cross platform - I believe the djinni-way is more novel, which is why we talked about it.  The scroll view example was interesting only because no one would really try to write a replacement; it is very complex.  The Cinder-way of writing a scroll view would mean to write an (OpenGL probably) scrolling view - which is silly in my opinion (albeit fun).  The CppCon talk showed how you can leverage platform-specific functionality when reinventing the wheel in a cross platform fashion doesn't really make sense.

The djinni-way and the Cinder-way are also not mutually exclusive.  For example, for Mailbox's networking stack we did the Cinder-way: we build libuv + openssl + json11 + libz for a websocket-ish realtime connection to our servers.  Adding Android and Mac to our iOS-only app was trivial from a networking side.

Last thing - Let's say someone needed to use Cinder with [Wake Locks](http://developer.android.com/reference/android/os/PowerManager.WakeLock.html) on an android device.  How would you go about doing that? I doubt that API is available in the c headers of android.

Anyway, I still think you are marrying the djinni with how Dropbox uses djinni a bit too much.  Djinni just lets you access C++ code in your native language (objc or Java).  

I gotta say, this is the most civil internet debate I've ever been a part of :+1:

**Comment by richardeakin** [comment]
Try using a native scrollview to do something [like this](https://vimeo.com/99379887#t=13s). :) (by the way, it is 8k x 4k resolution, real time motion blurred, all images are loaded async all the way up to the gpu).

For the android port we're having to route many things through jni, there is a layer abstracting that but you're right, not fun.  While we're trying to keep as much as possible in C++ and 'to the metal', it's unavoidable in many places (you mentioned one I wasn't aware of, video and capture are two others that just aren't exposed through the ndk yet).  The IDL approach seems helpful in this respect, but it comes at a bit of an expense if it requires incorporating a code generator + additional language (I see djini is written in scala). That's not to say we can't learn from your experiences, and I'm thankful to have seen the talk you guys did to explain your approach.

**Comment by skabbes** [comment]
holy crap - cool demo, seems like your world and mine are a bit apples to orange. best of luck, and hopefully we'll cross paths in the future.
