### ISSUE TITLE
iOS: Audio spikes/cuts when the screen is locked.

### ISSUE THREAD

**Issue by notlion** [cinder/Cinder#997]
If the screen is locked manually or the device goes to sleep while sound is playing a tone is played at full volume. After this happens all audio is muted on the device until it is rebooted.

I've tested this with the NodeBasic sample on an iPad Air 1st gen (iOS 8.3, current cinder/master), but have also seen the same behavior on an iPad Mini 1st gen.

Perhaps AVFoundation emits some callback we are expected to respond to by reducing the volume?

**Comment by richardeakin** [comment]
I'm probably not handling the iOS notifications right for when to pause / resume audio. It's long been on my TODO list, but I'd love it if someone using iOS more oftern than myself (almost never) were to look into it.

Here's what I think it is: I couldn't ever get [these notifications](https://github.com/cinder/Cinder/blob/master/src/cinder/audio/cocoa/DeviceManagerAudioSession.mm#L260-L285) to fire, once they are working, we can add some signal callbacks to DeviceManager, perhaps `getSignalInturruptionBegan()` and `getSignalInterruptionEnd()`. Then the audio::OutputDeviceNode can hook into these to pause / resume processing.

**Comment by richardeakin** [comment]
Oh, and we don't need to worry about the pre-iOS 6 route, we're bumping the min runtime target to 6 so that code should just be removed.

**Comment by richardeakin** [comment]
I finally had a chance to look at this and I can't say I have a solution. `AVAudioSessionInterruptionNotification` doesn't seem to fire when you hit the power button (although it does when you get a phone call), so I don't think the AVAudioSession notifications are any good to us.

Trying a different angle, using the `getSignalDidEnterBackground()` / `getSignalDidBecomeActive()`, which correspond to UIApplicationDelegate's `applicationDidEnterBackground:` and `applicationWillEnterForeground` appear to be too late - I get a sudden pop when I hit the power button, and when I come back there is no audio. Afterwards, the only way to get audio for any app is to restart the device, just as you found.

I'm curious what other projects are doing. Frankly, my knowledge of iOS is far outdated as I don't do much on that platform these days (and I dread having to try, since it usually takes more than an hour just to get an app to deploy to the device from Xcode). I'd like to find a solution to this nasty problem but I don't know of any.

**Comment by richardeakin** [comment]
Ah, a little hope - I'm able to register for `AppCocoaTouch::getSignalWillResignActive()` and disable the Context there - I still hear a pop and some audio ringing as if something is going through the buffer when I hit the power button, but at least when I turn the device back on I can hear audio again.

**Comment by notlion** [comment]
Hmm. Thanks again for looking into this, Rich. I read up on `AVAudioSessionInterruptionNotification` and came to the same conclusion you did. It's for phone calls and such and won't fire when the device sleeps.

My band-aid fix has been to call `audio::master()->deviceManager()->getDefaultInput()` to set the session category to `AVAudioSessionCategoryPlayAndRecord` which allows audio to play when the device is sleeping, and when the app is in the background. This has the side-effect of causing playback to not properly switch to a bluetooth speaker though, so it's not really a long term fix.

I wonder if there is a grace period from when `getSignalWillResignActive` is called where it's possible to fade the audio out. I'll give that a try.

**Comment by notlion** [comment]
I just tested disabling audio in the `getSignalWillResignActive` callback. It still emits a loud beep, and kills audio for me, forcing a restart every time. I also tried fading the audio out for 0.25s and 1.0s, both disabling the output after the sound had faded completely, and not. All result in the same behavior as long as the audio session is categorized as `AVAudioSessionCategoryAmbient`, which is the default (and arguably should be).

**Comment by notlion** [comment]
FWIW the libpd [Objective-C sample](https://github.com/libpd/libpd/tree/master/samples/objc/ios/pdtest) does not exhibit this behavior. Even when the category is set to `AVAudioSessionCategoryAmbient` the audio fades smoothly in and out. Comparing what Cinder is doing to the [libpd implementation](https://github.com/libpd/libpd/tree/master/objc) might be informative.

**Comment by richardeakin** [comment]
A different clue was reported [here](https://forum.libcinder.org/topic/simple-audio-graph-beating-when-the-screen-is-turned-off-on-ios-cinder-0-9#23286000002565001), where creating an InputDeviceNode (without connected to graph) suppresses the spike.

**Comment by notlion** [comment]
Does creating an input call `audio::DeviceManager::getDefaultInput()`? If so, it's the same as my workaround above, since `AVAudioSessionCategoryPlayAndRecord` causes audio to play in the background. Thus, no cut-outs when the app is backgrounded.

**Comment by richardeakin** [comment]
Ah, you're right - missed your note about that.. sorry for being daft, but you're saying that AVAudioSessionCategoryAmbient is the culprit? If so, I wonder about AVAudioSessionCategoryPlayback or AVAudioSessionCategorySoloAmbient as well, or how the other session categories respond. You can easily test out in your own code, at the end of your app setup() do something like the following (compiled as obj-c++):

```cpp
NSError *error = nil;
[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:&error];
```

If that works, maybe its just time that we add an option to DeviceManager that toggles optimal settings for playing in the background, with it only being functional on iOS for starters.

I really haven't had any time to look into what is different in libpd's implementation, or if there have been changes to it since I originally wrote it..

**Comment by notlion** [comment]
Here's the code in libpd that sets up the AudioSession category:

https://github.com/libpd/libpd/blob/cd26fab53e3b7f602bb859bc6cdbd0d13f571087/objc/PdAudioController.m#L164-L191

There must be something else that differs from what Cinder is doing, though. Even when that block is commented out and replaced with this, the audio still fades out nicely when the app is backgrounded.

```objc
[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:&error];
```

**Comment by notlion** [comment]
I made some progress on handing interruptions [here](https://github.com/notlion/Cinder/tree/fix-ios-audio) today.

Testing with BasicNode; If an alarm interrupts the app, audio now resumes. There's no fade-in, but i suppose that can be added by listening to the `getSignalInterruptionBegan()` and `getSignalInterruptionEnded()` signals that the DeviceManager now has. Which, is also as how the OutputNodes are notified of the interruption, as per your suggestion.

This unfortunately doesn't do anything to prevent the audio from killing the speaker on sleep, though..

**Comment by richardeakin** [comment]
Excellent progress, thank you @notlion! Yes I think handling the fade out / in is best done by the user since currently, we don't install a GainNode before sending out sound to the speakers. I believe only OS X has this feature built in (in the HAL audio unit) and so we decided to keep it slim at the graph level.

It is crazy that the sleep literally _kills_ audio - I've seen it too where you have to restart your phone in order to hear anything. This doesn't happen with libpd, or JUCE?
